# fly.toml app configuration file generated for sharefavorites-billowing-darkness-1530 on 2025-03-03T02:17:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sharefavorites-billowing-darkness-1530'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
